export default [
	{
		title: 'Dashboard',
		route: 'dashboard',
		icon: 'HomeIcon',
		resource: 'User',
		action:'read',
	},
	{
		title: 'Templates',
		route: 'templates',
		icon: 'LayoutIcon',
		resource: 'Operator',
		action:'read',
	},
	{
		title: 'Environment',
		route: 'environment',
		icon: 'GlobeIcon',
		resource: 'Operator',
		action:'read',
	},
	{
		title: 'Explore',
		route: 'explore',
		icon: 'CompassIcon',
		resource: 'User',
		action:'read',
	},
	{
		title: 'Cables',
		route: 'cables',
		icon: 'BoxIcon',
		resource: 'Operator',
		action:'read',
	},
	{
		title: 'Archive',
		route: 'archive',
		icon: 'ArchiveIcon',
		resource: 'Operator',
		action:'read',
	},
	{
		title: 'Admin',
		route: 'admin',
		icon: 'KeyIcon',
		resource: 'Administrator',
		action:'read',
	},
]